### ISSUE TITLE
[CMAKE ERROR] Could not find a package configuration file provided by   "ar_track_alvar_msgs" with any of the following names, when Doing catkin build 

### ISSUE THREAD

**Issue by maxwu8416** [hoodsr/birds-eye-view#2]
Hi there ! 
when i want to build (by using catkin build )the package there show up these several error 

![selection_005](https://user-images.githubusercontent.com/31397160/53944679-d7eac600-40fa-11e9-9252-778c541a49ca.png)
![selection_006](https://user-images.githubusercontent.com/31397160/53944684-dae5b680-40fa-11e9-8d54-cf10b5f25b1a.png)
![selection_007](https://user-images.githubusercontent.com/31397160/53944687-dcaf7a00-40fa-11e9-9b6a-ce8577e27570.png)
![selection_008](https://user-images.githubusercontent.com/31397160/53944707-e5a04b80-40fa-11e9-9a44-340ee62126f0.png)
![selection_009](https://user-images.githubusercontent.com/31397160/53944713-e802a580-40fa-11e9-8fb7-35e5df14b0fd.png)

these errors seems most of them are relative with package "ar_track_alvar", and missing some file, but no clue how to solved it. hope you can give some suggestion.  

here is all the package i put in the src folder don't it would be helpful.
![src_010](https://user-images.githubusercontent.com/31397160/53945094-c48c2a80-40fb-11e9-9836-05b435dd5051.png)

Hope someone can help me!!
Thanks !!

**Comment by Brenn10** [comment]
Have you installed ros-indigo-ar-track-alvar (sudo apt-get install ros-indigo-ar-track-alvar)?

**Comment by maxwu8416** [comment]
wow! thank you so much !  ar-track-alvar's problem has been solved !
but it comes out another error.

![selection_011](https://user-images.githubusercontent.com/31397160/53962778-e5b64080-4126-11e9-9e12-3d578a624512.png)

how can i fixed the .cpp code error ?

**Comment by maxwu8416** [comment]
hey~ i already solved that there is a little code error in the original source code

cd to /home/max/birds-eye-view/src/birds-eye-view/cooperative_localization/src edit file cl.cpp

fixed the error code " bebop.pose.pose.position.z " to " kbebop.pose.pose.position.z " at line 176 

![selection_012](https://user-images.githubusercontent.com/31397160/53964415-4c892900-412a-11e9-9dde-6f67be90a56c.png)
